INSERT INTO realisateur VALUES (1,'Woody Allen');
INSERT INTO realisateur VALUES (11,'Alfred Hitchcock');
INSERT INTO realisateur VALUES (18,'Steven Spielberg');
INSERT INTO realisateur VALUES (22,'Mel Gibson');
INSERT INTO realisateur VALUES (28,'Francis Ford Coppola');
INSERT INTO realisateur VALUES (37,'Rob Reiner');
INSERT INTO realisateur VALUES (47,'Mike Nichols');
INSERT INTO realisateur VALUES (59,'Terry Gilliam');
INSERT INTO realisateur VALUES (78,'Martin Scorsese');
INSERT INTO realisateur VALUES (79,'Billy Wilder');
INSERT INTO realisateur VALUES (80,'Sidney Lumet');
INSERT INTO realisateur VALUES (82,'Stanley Kubrick');
INSERT INTO realisateur VALUES (90,'Roman Polanski');
INSERT INTO realisateur VALUES (110,'Ridley Scott');
INSERT INTO realisateur VALUES (111,'Joel Coen');
INSERT INTO realisateur VALUES (139,'David Lynch');
INSERT INTO realisateur VALUES (140,'Wolfgang Petersen');
INSERT INTO realisateur VALUES (145,'Charles Chaplin');
INSERT INTO realisateur VALUES (197,'Howard Hawks');
INSERT INTO realisateur VALUES (198,'James Cameron');
INSERT INTO realisateur VALUES (204,'John Woo');
INSERT INTO realisateur VALUES (208,'Akira Kurosawa');
INSERT INTO realisateur VALUES (253,'Orson Welles');
INSERT INTO realisateur VALUES (268,'Sergio Leone');
INSERT INTO realisateur VALUES (273,'Ang Lee');
INSERT INTO realisateur VALUES (276,'George Roy Hill');
INSERT INTO realisateur VALUES (281,'Jonathan Demme');
INSERT INTO realisateur VALUES (287,'John Ford');
INSERT INTO realisateur VALUES (298,'Billy Bob Thornton');
INSERT INTO realisateur VALUES (312,'John Huston');
INSERT INTO realisateur VALUES (360,'George Lucas');
INSERT INTO realisateur VALUES (382,'Edward Zwick');
INSERT INTO realisateur VALUES (391,'Cameron Crowe');
INSERT INTO realisateur VALUES (392,'Frank Capra');
INSERT INTO realisateur VALUES (394,'Pedro Almodóvar');
INSERT INTO realisateur VALUES (398,'Krzysztof Kieslowski');
INSERT INTO realisateur VALUES (399,'Federico Fellini');
INSERT INTO realisateur VALUES (405,'Franklin J. Schaffner');
INSERT INTO realisateur VALUES (408,'Milos Forman');
INSERT INTO realisateur VALUES (414,'David Fincher');
INSERT INTO realisateur VALUES (420,'Ingmar Bergman');
INSERT INTO realisateur VALUES (428,'Stanley Donen');
INSERT INTO realisateur VALUES (444,'Quentin Tarantino');
INSERT INTO realisateur VALUES (505,'François Truffaut');
INSERT INTO realisateur VALUES (572,'Nick Park');
INSERT INTO realisateur VALUES (579,'Bob Clark (III)');
INSERT INTO realisateur VALUES (615,'Lars von Trier');
INSERT INTO realisateur VALUES (617,'Fred Zinnemann');
INSERT INTO realisateur VALUES (619,'Louis Malle');
INSERT INTO realisateur VALUES (620,'William Wyler');
INSERT INTO realisateur VALUES (628,'George Cukor');
INSERT INTO realisateur VALUES (639,'Bryan Singer');
INSERT INTO realisateur VALUES (651,'Irvin Kershner');
INSERT INTO realisateur VALUES (655,'Elia Kazan');
INSERT INTO realisateur VALUES (658,'Andrei Tarkovsky');
INSERT INTO realisateur VALUES (663,'Emir Kusturica');
INSERT INTO realisateur VALUES (675,'Michael Curtiz');
INSERT INTO realisateur VALUES (815,'Luis Buñuel');
INSERT INTO realisateur VALUES (820,'Roberto Benigni');
INSERT INTO realisateur VALUES (966,'M. Night Shyamalan');
INSERT INTO realisateur VALUES (992,'Leo McCarey');
INSERT INTO realisateur VALUES (1003,'Carol Reed');
INSERT INTO realisateur VALUES (1029,'Stuart Rosenberg (I)');
INSERT INTO realisateur VALUES (1040,'Frank Darabont');
INSERT INTO realisateur VALUES (1051,'Hayao Miyazaki');
INSERT INTO realisateur VALUES (1072,'Sam Peckinpah');
INSERT INTO realisateur VALUES (1080,'David Lean');
INSERT INTO realisateur VALUES (1097,'James Whale');
INSERT INTO realisateur VALUES (1106,'Michael Mann');
INSERT INTO realisateur VALUES (1111,'Joseph L. Mankiewicz');
INSERT INTO realisateur VALUES (1136,'Darren Aronofsky');
INSERT INTO realisateur VALUES (1151,'Victor Fleming');
INSERT INTO realisateur VALUES (1183,'Charles Laughton');
INSERT INTO realisateur VALUES (1406,'Otto Preminger');
INSERT INTO realisateur VALUES (1485,'Spike Jonze');
INSERT INTO realisateur VALUES (1886,'Werner Herzog');
INSERT INTO realisateur VALUES (2014,'Ernst Lubitsch');
INSERT INTO realisateur VALUES (2031,'Fax Bahr');
INSERT INTO realisateur VALUES (2035,'F.W. Murnau');
INSERT INTO realisateur VALUES (2043,'Ash Brannon');
INSERT INTO realisateur VALUES (2073,'Erick Zonca');
INSERT INTO realisateur VALUES (2128,'Grigori Aleksandrov');
INSERT INTO realisateur VALUES (2138,'Lewis Milestone');
INSERT INTO realisateur VALUES (2142,'Giuseppe Tornatore');
INSERT INTO realisateur VALUES (2205,'Guy Ritchie');
INSERT INTO realisateur VALUES (2292,'Jean Renoir');
INSERT INTO realisateur VALUES (2343,'Clyde Bruckman');
INSERT INTO realisateur VALUES (2401,'Isao Takahata');
INSERT INTO realisateur VALUES (2434,'Brian Desmond Hurst');
INSERT INTO realisateur VALUES (2473,'John Sturges');
INSERT INTO realisateur VALUES (2532,'Sam Wood');
INSERT INTO realisateur VALUES (2542,'Sam Mendes');
INSERT INTO realisateur VALUES (2560,'Walter Salles');
INSERT INTO realisateur VALUES (2564,'W.S. Van Dyke');
INSERT INTO realisateur VALUES (2573,'Marcel Carné');
INSERT INTO realisateur VALUES (2586,'Robert Mulligan');
INSERT INTO realisateur VALUES (2605,'Robert Rossen');
INSERT INTO realisateur VALUES (2645,'Michael Cimino');
INSERT INTO realisateur VALUES (2663,'Tony Kaye (I)');
INSERT INTO realisateur VALUES (2717,'Melvin Frank');
INSERT INTO realisateur VALUES (2784,'Stephen Daldry');
INSERT INTO realisateur VALUES (2803,'Lukas Moodysson');
INSERT INTO realisateur VALUES (2830,'Yimou Zhang');