INSERT INTO acteur VALUES (1,'Woody Allen');
INSERT INTO acteur VALUES (2,'Clint Eastwood');
INSERT INTO acteur VALUES (3,'Robert De Niro');
INSERT INTO acteur VALUES (6,'Harrison Ford');
INSERT INTO acteur VALUES (8,'Tom Hanks');
INSERT INTO acteur VALUES (12,'Al Pacino');
INSERT INTO acteur VALUES (13,'Bruce Willis');
INSERT INTO acteur VALUES (16,'Gene Hackman');
INSERT INTO acteur VALUES (24,'Danny DeVito');
INSERT INTO acteur VALUES (25,'Tim Robbins');
INSERT INTO acteur VALUES (27,'Dustin Hoffman');
INSERT INTO acteur VALUES (28,'Francis Ford Coppola');
INSERT INTO acteur VALUES (32,'John Cusack');
INSERT INTO acteur VALUES (34,'John Travolta');
INSERT INTO acteur VALUES (36,'Robert Redford');
INSERT INTO acteur VALUES (39,'Anthony Hopkins');
INSERT INTO acteur VALUES (41,'Denzel Washington');
INSERT INTO acteur VALUES (42,'Paul Newman');
INSERT INTO acteur VALUES (43,'Jack Nicholson');
INSERT INTO acteur VALUES (44,'Robert Duvall');
INSERT INTO acteur VALUES (50,'Matthew Broderick');
INSERT INTO acteur VALUES (54,'Sigourney Weaver');
INSERT INTO acteur VALUES (59,'Terry Gilliam');
INSERT INTO acteur VALUES (63,'Meryl Streep');
INSERT INTO acteur VALUES (73,'Harvey Keitel');
INSERT INTO acteur VALUES (75,'Cary Grant');
INSERT INTO acteur VALUES (76,'Kevin Spacey');
INSERT INTO acteur VALUES (85,'Marlon Brando');
INSERT INTO acteur VALUES (89,'Samuel L. Jackson');
INSERT INTO acteur VALUES (90,'Roman Polanski');
INSERT INTO acteur VALUES (91,'Morgan Freeman');
INSERT INTO acteur VALUES (94,'Diane Keaton');
INSERT INTO acteur VALUES (99,'Christopher Walken');
INSERT INTO acteur VALUES (100,'Liam Neeson');
INSERT INTO acteur VALUES (106,'Jack Lemmon');
INSERT INTO acteur VALUES (115,'Peter Sellers');
INSERT INTO acteur VALUES (118,'James Stewart');
INSERT INTO acteur VALUES (123,'Frank Oz');
INSERT INTO acteur VALUES (125,'Dennis Hopper');
INSERT INTO acteur VALUES (127,'Jack Warden');
INSERT INTO acteur VALUES (130,'Bill Paxton');
INSERT INTO acteur VALUES (145,'Charles Chaplin');
INSERT INTO acteur VALUES (152,'Joan Cusack');
INSERT INTO acteur VALUES (158,'Billy Crystal');
INSERT INTO acteur VALUES (160,'Max von Sydow');
INSERT INTO acteur VALUES (164,'Gregory Peck');
INSERT INTO acteur VALUES (165,'Charlton Heston');
INSERT INTO acteur VALUES (167,'Donald Pleasence');
INSERT INTO acteur VALUES (170,'John Wayne');
INSERT INTO acteur VALUES (177,'Ralph Fiennes');
INSERT INTO acteur VALUES (181,'Matt Damon');
INSERT INTO acteur VALUES (182,'Faye Dunaway');
INSERT INTO acteur VALUES (183,'William Holden');
INSERT INTO acteur VALUES (186,'Steve Buscemi');
INSERT INTO acteur VALUES (195,'John Cleese');
INSERT INTO acteur VALUES (211,'Gwyneth Paltrow');
INSERT INTO acteur VALUES (213,'Humphrey Bogart');
INSERT INTO acteur VALUES (215,'Jodie Foster');
INSERT INTO acteur VALUES (217,'J.T. Walsh');
INSERT INTO acteur VALUES (222,'Cary Elwes');
INSERT INTO acteur VALUES (225,'Anne Bancroft');
INSERT INTO acteur VALUES (226,'William H. Macy');
INSERT INTO acteur VALUES (235,'Richard Attenborough');
INSERT INTO acteur VALUES (239,'Ian Holm');
INSERT INTO acteur VALUES (243,'Uma Thurman');
INSERT INTO acteur VALUES (244,'Michael Madsen');
INSERT INTO acteur VALUES (246,'Dan Hedaya');
INSERT INTO acteur VALUES (247,'Albert Brooks');
INSERT INTO acteur VALUES (249,'Annette Bening');
INSERT INTO acteur VALUES (250,'James Caan');
INSERT INTO acteur VALUES (252,'Lance Henriksen');
INSERT INTO acteur VALUES (253,'Orson Welles');
INSERT INTO acteur VALUES (258,'Brad Pitt');
INSERT INTO acteur VALUES (259,'Joe Pesci');
INSERT INTO acteur VALUES (279,'Steve McQueen');
INSERT INTO acteur VALUES (282,'Cameron Diaz');
INSERT INTO acteur VALUES (295,'Harry Dean Stanton');
INSERT INTO acteur VALUES (298,'Billy Bob Thornton');
INSERT INTO acteur VALUES (301,'Peter Boyle');
INSERT INTO acteur VALUES (302,'Benicio Del Toro');
INSERT INTO acteur VALUES (304,'Malcolm McDowell');
INSERT INTO acteur VALUES (306,'Martin Sheen');
INSERT INTO acteur VALUES (307,'Bonnie Hunt');
INSERT INTO acteur VALUES (308,'Gabriel Byrne');
INSERT INTO acteur VALUES (312,'John Huston');
INSERT INTO acteur VALUES (318,'Tom Sizemore');
INSERT INTO acteur VALUES (324,'Russell Crowe');
INSERT INTO acteur VALUES (329,'Ben Kingsley');
INSERT INTO acteur VALUES (331,'Laurence Fishburne');
INSERT INTO acteur VALUES (333,'Minnie Driver');
INSERT INTO acteur VALUES (336,'J�rgen Prochnow');
INSERT INTO acteur VALUES (340,'Shirley MacLaine');
INSERT INTO acteur VALUES (342,'Claire Danes');
INSERT INTO acteur VALUES (345,'Henry Fonda');
INSERT INTO acteur VALUES (348,'Giovanni Ribisi');
INSERT INTO acteur VALUES (352,'Christopher Guest');
INSERT INTO acteur VALUES (354,'Charles Durning');
INSERT INTO acteur VALUES (355,'Ving Rhames');
INSERT INTO acteur VALUES (356,'Tom Skerritt');
INSERT INTO acteur VALUES (357,'Bruno Kirby');
INSERT INTO acteur VALUES (360,'George Lucas');
INSERT INTO acteur VALUES (368,'Rosanna Arquette');
INSERT INTO acteur VALUES (370,'Laurence Olivier');
INSERT INTO acteur VALUES (373,'Lloyd Bridges');
INSERT INTO acteur VALUES (393,'Yun-Fat Chow');
INSERT INTO acteur VALUES (404,'Kirk Douglas');
INSERT INTO acteur VALUES (417,'David Morse');
INSERT INTO acteur VALUES (427,'Edward Norton');
INSERT INTO acteur VALUES (429,'Katharine Hepburn');
INSERT INTO acteur VALUES (431,'James Cromwell');
INSERT INTO acteur VALUES (436,'Carol Kane');
INSERT INTO acteur VALUES (437,'M. Emmet Walsh');
INSERT INTO acteur VALUES (438,'John Hurt');
INSERT INTO acteur VALUES (439,'Jeffrey Jones');
INSERT INTO acteur VALUES (441,'Chazz Palminteri');
INSERT INTO acteur VALUES (442,'Joaquin Phoenix');
INSERT INTO acteur VALUES (443,'Philip Seymour Hoffman');
INSERT INTO acteur VALUES (444,'Quentin Tarantino');
INSERT INTO acteur VALUES (449,'Vincent D''Onofrio');
INSERT INTO acteur VALUES (453,'Martin Balsam');
INSERT INTO acteur VALUES (460,'Giancarlo Esposito');
INSERT INTO acteur VALUES (462,'Carrie Fisher');
INSERT INTO acteur VALUES (463,'Sissy Spacek');
INSERT INTO acteur VALUES (472,'James Coburn');
INSERT INTO acteur VALUES (474,'Natalie Wood');
INSERT INTO acteur VALUES (476,'George Kennedy');
INSERT INTO acteur VALUES (479,'George C. Scott');
INSERT INTO acteur VALUES (481,'Oliver Reed');
INSERT INTO acteur VALUES (482,'R. Lee Ermey');
INSERT INTO acteur VALUES (485,'Edward Burns (I)');
INSERT INTO acteur VALUES (489,'Don Taylor (I)');
INSERT INTO acteur VALUES (493,'Michael Biehn');
INSERT INTO acteur VALUES (494,'Cloris Leachman');
INSERT INTO acteur VALUES (495,'Frances McDormand');
INSERT INTO acteur VALUES (496,'Catherine Deneuve');
INSERT INTO acteur VALUES (502,'Talia Shire');
INSERT INTO acteur VALUES (503,'John Malkovich');
INSERT INTO acteur VALUES (507,'Bob Gunton');
INSERT INTO acteur VALUES (509,'Simon Callow');
INSERT INTO acteur VALUES (512,'Matthew Modine');
INSERT INTO acteur VALUES (515,'Brion James');
INSERT INTO acteur VALUES (518,'Martin Landau');
INSERT INTO acteur VALUES (519,'Christopher Plummer');
INSERT INTO acteur VALUES (520,'Stephen Tobolowsky');
INSERT INTO acteur VALUES (527,'Denholm Elliott');
INSERT INTO acteur VALUES (528,'Kevin Pollak');
INSERT INTO acteur VALUES (534,'Lauren Bacall');
INSERT INTO acteur VALUES (536,'Robin Wright');
INSERT INTO acteur VALUES (539,'Elizabeth Taylor');
INSERT INTO acteur VALUES (541,'Lindsay Crouse');
INSERT INTO acteur VALUES (546,'James Earl Jones');
INSERT INTO acteur VALUES (549,'Gina Gershon');
INSERT INTO acteur VALUES (550,'Ben Gazzara');
INSERT INTO acteur VALUES (552,'Mark Hamill');
INSERT INTO acteur VALUES (554,'Hume Cronyn');
INSERT INTO acteur VALUES (555,'Teri Garr');
INSERT INTO acteur VALUES (558,'Shelley Duvall');
INSERT INTO acteur VALUES (560,'Philip Baker Hall');
INSERT INTO acteur VALUES (578,'Toni Collette');
INSERT INTO acteur VALUES (587,'Mike Starr (I)');
INSERT INTO acteur VALUES (591,'Daryl Hannah');
INSERT INTO acteur VALUES (594,'Beverly D''Angelo');
INSERT INTO acteur VALUES (625,'Peter Sallis');
INSERT INTO acteur VALUES (626,'Gene Kelly');
INSERT INTO acteur VALUES (629,'George Dzundza');
INSERT INTO acteur VALUES (634,'Graham Chapman');
INSERT INTO acteur VALUES (643,'Veronica Cartwright');
INSERT INTO acteur VALUES (680,'Chris Sarandon');
INSERT INTO acteur VALUES (682,'Melinda Dillon');
INSERT INTO acteur VALUES (684,'Tim Allen');
INSERT INTO acteur VALUES (687,'John Ritter');
INSERT INTO acteur VALUES (688,'Takashi Shimura');
INSERT INTO acteur VALUES (693,'John Milius');
INSERT INTO acteur VALUES (694,'Terry Jones');
INSERT INTO acteur VALUES (698,'Keith David (I)');
INSERT INTO acteur VALUES (702,'Eric Stoltz');
INSERT INTO acteur VALUES (710,'Chris Penn');
INSERT INTO acteur VALUES (711,'Murray Hamilton');
INSERT INTO acteur VALUES (713,'Brian Cox');
INSERT INTO acteur VALUES (716,'Helena Bonham Carter');
INSERT INTO acteur VALUES (719,'Warren Oates');
INSERT INTO acteur VALUES (722,'Ernest Borgnine');
INSERT INTO acteur VALUES (725,'Eileen Brennan');
INSERT INTO acteur VALUES (728,'Chris Cooper (I)');
INSERT INTO acteur VALUES (731,'William Daniels (I)');
INSERT INTO acteur VALUES (735,'Toshir� Mifune');
INSERT INTO acteur VALUES (736,'Embeth Davidtz');
INSERT INTO acteur VALUES (743,'Rip Torn');
INSERT INTO acteur VALUES (745,'Udo Kier');
INSERT INTO acteur VALUES (747,'Scott Glenn');
INSERT INTO acteur VALUES (749,'Eric Idle');
INSERT INTO acteur VALUES (751,'Rod Steiger');
INSERT INTO acteur VALUES (752,'Dennis Farina');
INSERT INTO acteur VALUES (757,'Ray Walston');
INSERT INTO acteur VALUES (762,'Debi Mazar');
INSERT INTO acteur VALUES (763,'Louise Fletcher');
INSERT INTO acteur VALUES (770,'Fairuza Balk');
INSERT INTO acteur VALUES (775,'Rade Serbedzija');
INSERT INTO acteur VALUES (776,'Ray Liotta');
INSERT INTO acteur VALUES (780,'Joseph Cotten');
INSERT INTO acteur VALUES (791,'Tim Roth');
INSERT INTO acteur VALUES (792,'Jean-Marc Barr');
INSERT INTO acteur VALUES (799,'Michael Palin');
INSERT INTO acteur VALUES (802,'James Mason');
INSERT INTO acteur VALUES (805,'Richard Burton');
INSERT INTO acteur VALUES (811,'Ir�ne Jacob');
INSERT INTO acteur VALUES (815,'Luis Bu�uel');
INSERT INTO acteur VALUES (820,'Roberto Benigni');
INSERT INTO acteur VALUES (827,'Ingrid Bergman');
INSERT INTO acteur VALUES (828,'Bette Davis');
INSERT INTO acteur VALUES (831,'Edward Furlong');
INSERT INTO acteur VALUES (833,'Colleen Camp');
INSERT INTO acteur VALUES (837,'John Carradine');
INSERT INTO acteur VALUES (839,'Bernard Lee (I)');
INSERT INTO acteur VALUES (845,'Robert Stack');
INSERT INTO acteur VALUES (849,'Amanda Plummer');
INSERT INTO acteur VALUES (862,'Pete Postlethwaite');
INSERT INTO acteur VALUES (881,'Peter Gallagher');
INSERT INTO acteur VALUES (887,'Ed O''Ross');
INSERT INTO acteur VALUES (891,'Tom Hulce');
INSERT INTO acteur VALUES (892,'Teresa Wright');
INSERT INTO acteur VALUES (893,'James Garner');
INSERT INTO acteur VALUES (899,'Gunnar Bj�rnstrand');
INSERT INTO acteur VALUES (900,'Strother Martin');
INSERT INTO acteur VALUES (907,'Joe Grifasi');
INSERT INTO acteur VALUES (915,'Marilyn Monroe');
INSERT INTO acteur VALUES (925,'Alec Guinness');
INSERT INTO acteur VALUES (930,'John Savage');
INSERT INTO acteur VALUES (933,'Karen Allen');
INSERT INTO acteur VALUES (937,'John Cazale');
INSERT INTO acteur VALUES (938,'Kim Hunter');
INSERT INTO acteur VALUES (941,'Robert Mitchum');
INSERT INTO acteur VALUES (943,'Anthony Quinn');
INSERT INTO acteur VALUES (946,'Gillian Anderson');
INSERT INTO acteur VALUES (947,'Elliott Gould');
INSERT INTO acteur VALUES (963,'Allen Garfield');
INSERT INTO acteur VALUES (964,'F. Murray Abraham');
INSERT INTO acteur VALUES (969,'Thora Birch');
INSERT INTO acteur VALUES (981,'Groucho Marx');
INSERT INTO acteur VALUES (984,'William Sadler');
INSERT INTO acteur VALUES (986,'Caroline Goodall');
INSERT INTO acteur VALUES (1005,'Edward James Olmos');
INSERT INTO acteur VALUES (1024,'Pen�lope Cruz');
INSERT INTO acteur VALUES (1031,'Grace Kelly');
INSERT INTO acteur VALUES (1038,'Paul Sorvino');
INSERT INTO acteur VALUES (1045,'Fred MacMurray');
INSERT INTO acteur VALUES (1056,'George Sanders');
INSERT INTO acteur VALUES (1077,'Thomas Mitchell (I)');
INSERT INTO acteur VALUES (1100,'Rutger Hauer');
INSERT INTO acteur VALUES (1108,'Clark Gable');
INSERT INTO acteur VALUES (1128,'Claude Rains');
INSERT INTO acteur VALUES (1145,'Sean Young');
INSERT INTO acteur VALUES (1148,'Bibi Andersson');
INSERT INTO acteur VALUES (1162,'Don Rickles');
INSERT INTO acteur VALUES (1165,'Kelsey Grammer');
INSERT INTO acteur VALUES (1176,'Diane Venora');
INSERT INTO acteur VALUES (1181,'Annie Potts');
INSERT INTO acteur VALUES (1183,'Charles Laughton');
INSERT INTO acteur VALUES (1184,'Robert Shaw');
INSERT INTO acteur VALUES (1187,'Patricia Clarkson');
INSERT INTO acteur VALUES (1195,'Ted Danson');
INSERT INTO acteur VALUES (1198,'Frederic Forrest');
INSERT INTO acteur VALUES (1202,'Clancy Brown');
INSERT INTO acteur VALUES (1207,'Anna Paquin');
INSERT INTO acteur VALUES (1215,'Jason Lee (I)');
INSERT INTO acteur VALUES (1217,'Everett McGill');
INSERT INTO acteur VALUES (1221,'Peter Falk');
INSERT INTO acteur VALUES (1222,'Wallace Shawn');
INSERT INTO acteur VALUES (1230,'E.G. Marshall');
INSERT INTO acteur VALUES (1231,'Ralph Bellamy');
INSERT INTO acteur VALUES (1232,'Kasi Lemmons');
INSERT INTO acteur VALUES (1233,'Cliff De Young');
INSERT INTO acteur VALUES (1234,'Michael Gambon');
INSERT INTO acteur VALUES (1239,'James Hampton');
INSERT INTO acteur VALUES (1242,'Jeffrey DeMunn');
INSERT INTO acteur VALUES (1243,'Stephen Baldwin');
INSERT INTO acteur VALUES (1248,'Connie Nielsen');
INSERT INTO acteur VALUES (1249,'Tony Burton');
INSERT INTO acteur VALUES (1250,'Vin Diesel');
INSERT INTO acteur VALUES (1252,'Piper Laurie');
INSERT INTO acteur VALUES (1255,'Graham Greene (II)');
INSERT INTO acteur VALUES (1257,'George Segal');
INSERT INTO acteur VALUES (1266,'Yaphet Kotto');
INSERT INTO acteur VALUES (1276,'Ward Bond');
INSERT INTO acteur VALUES (1286,'Andre Braugher');
INSERT INTO acteur VALUES (1290,'Henry Jones (I)');
INSERT INTO acteur VALUES (1305,'Tony Roberts (I)');
INSERT INTO acteur VALUES (1308,'Michael Jeter');
INSERT INTO acteur VALUES (1310,'Bruce McGill');
INSERT INTO acteur VALUES (1313,'Peter Stormare');
INSERT INTO acteur VALUES (1314,'Patrick McGoohan');
INSERT INTO acteur VALUES (1322,'Leo G. Carroll');
INSERT INTO acteur VALUES (1323,'Cathy Moriarty');
INSERT INTO acteur VALUES (1329,'Paul Bartel');
INSERT INTO acteur VALUES (1333,'Kenneth Mars');
INSERT INTO acteur VALUES (1336,'Porter Hall');
INSERT INTO acteur VALUES (1342,'James Cosmo');
INSERT INTO acteur VALUES (1344,'Joanna Cassidy');
INSERT INTO acteur VALUES (1346,'Jack MacGowran');
INSERT INTO acteur VALUES (1351,'Lee Van Cleef');
INSERT INTO acteur VALUES (1353,'Jason Robards');
INSERT INTO acteur VALUES (1370,'Ed Binns');
INSERT INTO acteur VALUES (1376,'Billy Crudup');
INSERT INTO acteur VALUES (1377,'Wallace Ford');
INSERT INTO acteur VALUES (1390,'Claudia Cardinale');
INSERT INTO acteur VALUES (1396,'Tony Darrow');
INSERT INTO acteur VALUES (1402,'Mary Kay Place');
INSERT INTO acteur VALUES (1406,'Otto Preminger');
INSERT INTO acteur VALUES (1414,'Olivia Williams');
INSERT INTO acteur VALUES (1419,'Katharine Ross');
INSERT INTO acteur VALUES (1420,'Elizabeth Wilson (I)');
INSERT INTO acteur VALUES (1427,'Keir Dullea');
INSERT INTO acteur VALUES (1430,'Marco Leonardi');
INSERT INTO acteur VALUES (1437,'Trevor Howard');
INSERT INTO acteur VALUES (1438,'Rosalind Russell');
INSERT INTO acteur VALUES (1442,'Karl Malden');
INSERT INTO acteur VALUES (1443,'Julie Walters');
INSERT INTO acteur VALUES (1449,'Jack Hawkins');
INSERT INTO acteur VALUES (1450,'James Hong');
INSERT INTO acteur VALUES (1453,'Sterling Hayden');
INSERT INTO acteur VALUES (1458,'Roy Dotrice');
INSERT INTO acteur VALUES (1461,'Danny Kaye');
INSERT INTO acteur VALUES (1464,'Myrna Loy');
INSERT INTO acteur VALUES (1467,'Charles Bronson');
INSERT INTO acteur VALUES (1471,'Sofia Coppola');
INSERT INTO acteur VALUES (1472,'Michelle Yeoh');
INSERT INTO acteur VALUES (1476,'Sihung Lung');
INSERT INTO acteur VALUES (1488,'Maureen O''Hara');
INSERT INTO acteur VALUES (1491,'Ruth Warrick');
INSERT INTO acteur VALUES (1496,'John Williams (II)');
INSERT INTO acteur VALUES (1509,'Jean Arthur');
INSERT INTO acteur VALUES (1524,'Vivien Leigh');
INSERT INTO acteur VALUES (1526,'Warren Clarke');
INSERT INTO acteur VALUES (1527,'Farley Granger');
INSERT INTO acteur VALUES (1536,'Walter Brennan');
INSERT INTO acteur VALUES (1543,'William Powell');
INSERT INTO acteur VALUES (1544,'Akira Terao');
INSERT INTO acteur VALUES (1545,'Lee J. Cobb');
INSERT INTO acteur VALUES (1546,'Angela Lansbury');
INSERT INTO acteur VALUES (1552,'Richard Farnsworth');
INSERT INTO acteur VALUES (1553,'Glynis Johns');
INSERT INTO acteur VALUES (1554,'Kenneth Tsang');
INSERT INTO acteur VALUES (1557,'Peter Graves (I)');
INSERT INTO acteur VALUES (1565,'Allison Janney');
INSERT INTO acteur VALUES (1570,'Frankie Faison');
INSERT INTO acteur VALUES (1574,'Derek Jacobi');
INSERT INTO acteur VALUES (1576,'Anthony Heald');
INSERT INTO acteur VALUES (1579,'Ronald Lacey');
INSERT INTO acteur VALUES (1582,'G.D. Spradlin');
INSERT INTO acteur VALUES (1586,'Jeff Corey');
INSERT INTO acteur VALUES (1591,'Sam Rockwell');
INSERT INTO acteur VALUES (1615,'Lorraine Bracco');
INSERT INTO acteur VALUES (1619,'Lena Olin');
INSERT INTO acteur VALUES (1623,'Albert Hall (I)');
INSERT INTO acteur VALUES (1640,'Paul Giamatti');
INSERT INTO acteur VALUES (1651,'Judith Anderson');
INSERT INTO acteur VALUES (1653,'Barry Pepper');
INSERT INTO acteur VALUES (1655,'Anthony Daniels');
INSERT INTO acteur VALUES (1660,'James Whitmore');
INSERT INTO acteur VALUES (1669,'Elsa Lanchester');
INSERT INTO acteur VALUES (1678,'John Rhys-Davies');
INSERT INTO acteur VALUES (1679,'Edward G. Robinson');
INSERT INTO acteur VALUES (1698,'Tatsuya Nakadai');
INSERT INTO acteur VALUES (1704,'Darren McGavin');
INSERT INTO acteur VALUES (1709,'Cybill Shepherd');
INSERT INTO acteur VALUES (1715,'Michael Clarke Duncan');
INSERT INTO acteur VALUES (1717,'Janet Leigh');
INSERT INTO acteur VALUES (1720,'Michael Bates (I)');
INSERT INTO acteur VALUES (1725,'Stacy Keach');
INSERT INTO acteur VALUES (1726,'Ben Johnson (I)');
INSERT INTO acteur VALUES (1727,'Billy Dee Williams');
INSERT INTO acteur VALUES (1736,'Christine Ebersole');
INSERT INTO acteur VALUES (1742,'Harry Morgan');
INSERT INTO acteur VALUES (1743,'Pupella Maggio');
INSERT INTO acteur VALUES (1748,'Wayne Knight');
INSERT INTO acteur VALUES (1750,'Slim Pickens');
INSERT INTO acteur VALUES (1762,'Colm Feore');
INSERT INTO acteur VALUES (1766,'Lew Ayres');
INSERT INTO acteur VALUES (1772,'Anatoli Solonitsyn');
INSERT INTO acteur VALUES (1774,'Keenan Wynn');
INSERT INTO acteur VALUES (1781,'Joel Grey');
INSERT INTO acteur VALUES (1784,'Victor Argo');
INSERT INTO acteur VALUES (1789,'Mildred Natwick');
INSERT INTO acteur VALUES (1792,'Jack Kehoe');
INSERT INTO acteur VALUES (1797,'Stefan Gierasch');
INSERT INTO acteur VALUES (1801,'Jenette Goldstein');
INSERT INTO acteur VALUES (1802,'Zach Grenier');
INSERT INTO acteur VALUES (1803,'Zeljko Ivanek');
INSERT INTO acteur VALUES (1808,'Mark Rolston');
INSERT INTO acteur VALUES (1813,'Richard Harris');
INSERT INTO acteur VALUES (1814,'David Proval');
INSERT INTO acteur VALUES (1817,'Frank Vincent (I)');
INSERT INTO acteur VALUES (1824,'William Windom');
INSERT INTO acteur VALUES (1827,'Laurie Metcalf');
INSERT INTO acteur VALUES (1831,'Adam Baldwin');
INSERT INTO acteur VALUES (1835,'Patrick Magee (I)');
INSERT INTO acteur VALUES (1845,'Robert Webber (I)');
INSERT INTO acteur VALUES (1847,'John Hillerman');
INSERT INTO acteur VALUES (1860,'Billy Gilbert (I)');
INSERT INTO acteur VALUES (1864,'Mel Smith');
INSERT INTO acteur VALUES (1868,'Suzy Amis');
INSERT INTO acteur VALUES (1881,'Abe Vigoda');
INSERT INTO acteur VALUES (1895,'Ted Levine');
INSERT INTO acteur VALUES (1901,'Leslie Carlson');
INSERT INTO acteur VALUES (1906,'Cecil B. DeMille');
INSERT INTO acteur VALUES (1909,'Barry Dennen');
INSERT INTO acteur VALUES (1913,'Adam Goldberg');
INSERT INTO acteur VALUES (1933,'Paul Reiser');
INSERT INTO acteur VALUES (1939,'Sean McGinley');
INSERT INTO acteur VALUES (1946,'Minoru Chiaki');
INSERT INTO acteur VALUES (1951,'Jeremy Davies');
INSERT INTO acteur VALUES (1953,'Ethan Suplee');
INSERT INTO acteur VALUES (1961,'Nicoletta Braschi');
INSERT INTO acteur VALUES (1966,'Djimon Hounsou');
INSERT INTO acteur VALUES (1976,'Erland Josephson');
INSERT INTO acteur VALUES (1977,'Jean-Pierre L�aud');
INSERT INTO acteur VALUES (1985,'Jessie Royce Landis');
INSERT INTO acteur VALUES (1989,'Robert J. Wilke');
INSERT INTO acteur VALUES (1996,'Miki Manojlovic');
INSERT INTO acteur VALUES (2000,'Barry Fitzgerald');
INSERT INTO acteur VALUES (2003,'Anne Baxter');
INSERT INTO acteur VALUES (2009,'Errol Flynn');
INSERT INTO acteur VALUES (2012,'Henry Travers');
INSERT INTO acteur VALUES (2030,'Fernanda Montenegro');
INSERT INTO acteur VALUES (2034,'Henry Bergman');
INSERT INTO acteur VALUES (2049,'Arletty');
INSERT INTO acteur VALUES (2070,'Kamatari Fujiwara');
INSERT INTO acteur VALUES (2076,'Erich von Stroheim');
INSERT INTO acteur VALUES (2078,'Hermione Baddeley');
INSERT INTO acteur VALUES (2081,'Eli Wallach');
INSERT INTO acteur VALUES (2083,'Antonella Attili');
INSERT INTO acteur VALUES (2085,'Bajram Severdzan');
INSERT INTO acteur VALUES (2100,'Gene Lockhart');
INSERT INTO acteur VALUES (2104,'Gaspard Manesse');
INSERT INTO acteur VALUES (2113,'Alastair Sim');
INSERT INTO acteur VALUES (2123,'Lee Remick');
INSERT INTO acteur VALUES (2141,'Gladys Cooper');
INSERT INTO acteur VALUES (2143,'élodie Bouchez');
INSERT INTO acteur VALUES (2147,'Gary Cooper');
INSERT INTO acteur VALUES (2159,'Gr�goire Colin');
INSERT INTO acteur VALUES (2171,'Frank Overton');
INSERT INTO acteur VALUES (2173,'Harpo Marx');
INSERT INTO acteur VALUES (2177,'Kristina Adolphson');
INSERT INTO acteur VALUES (2192,'Basil Rathbone');
INSERT INTO acteur VALUES (2198,'Fred Clark (I)');
INSERT INTO acteur VALUES (2202,'Gabriele Ferzetti');
INSERT INTO acteur VALUES (2210,'Gustav Botz');
INSERT INTO acteur VALUES (2225,'Haley Joel Osment');
INSERT INTO acteur VALUES (2227,'Fredric March');
INSERT INTO acteur VALUES (2229,'Alexandra Dahlstr�m');
INSERT INTO acteur VALUES (2238,'Carole Lombard');
INSERT INTO acteur VALUES (2246,'Cecilia Roth');
INSERT INTO acteur VALUES (2268,'Jean Gabin');
INSERT INTO acteur VALUES (2313,'Claire Trevor');
INSERT INTO acteur VALUES (2319,'Cindy Williams (I)');
INSERT INTO acteur VALUES (2321,'Joan Fontaine');
INSERT INTO acteur VALUES (2329,'Chico Marx');
INSERT INTO acteur VALUES (2333,'Jennifer Lien');
INSERT INTO acteur VALUES (2381,'Bj�rk');
INSERT INTO acteur VALUES (2393,'Jack Carson (I)');
INSERT INTO acteur VALUES (2396,'Jack Kruschen');
INSERT INTO acteur VALUES (2412,'Judy Garland');
INSERT INTO acteur VALUES (2416,'Dorian Harewood');
INSERT INTO acteur VALUES (2446,'James Robinson (II)');
INSERT INTO acteur VALUES (2465,'James Donald (I)');
INSERT INTO acteur VALUES (2475,'Debbie Reynolds');
INSERT INTO acteur VALUES (2484,'Boris Karloff');
INSERT INTO acteur VALUES (2486,'Olivia de Havilland');
INSERT INTO acteur VALUES (2495,'Sam Bottoms');
INSERT INTO acteur VALUES (2505,'Vincent Gardenia');
INSERT INTO acteur VALUES (2534,'Nikolai Grinko');
INSERT INTO acteur VALUES (2538,'Victor Sj�str�m');
INSERT INTO acteur VALUES (2553,'Robert Strauss (I)');
INSERT INTO acteur VALUES (2576,'Paul Freeman (I)');
INSERT INTO acteur VALUES (2604,'Marion Mack');
INSERT INTO acteur VALUES (2624,'Michael Hordern');
INSERT INTO acteur VALUES (2635,'Vera Miles');
INSERT INTO acteur VALUES (2648,'Michael Constantine');
INSERT INTO acteur VALUES (2649,'Tom Helmore');
INSERT INTO acteur VALUES (2650,'Tsutomu Tatsumi');
INSERT INTO acteur VALUES (2662,'Tony Curtis');
INSERT INTO acteur VALUES (2672,'Mieko Harada');
INSERT INTO acteur VALUES (2723,'Maureen O''Sullivan');
INSERT INTO acteur VALUES (2724,'Montgomery Clift');
INSERT INTO acteur VALUES (2728,'Tyrone Power');
INSERT INTO acteur VALUES (2748,'Robert Morley (I)');
INSERT INTO acteur VALUES (2773,'Magali No�l');
INSERT INTO acteur VALUES (2792,'Peter Lorre');
INSERT INTO acteur VALUES (2800,'Y�ji Matsuda');
INSERT INTO acteur VALUES (2812,'Luigi Pistilli');
INSERT INTO acteur VALUES (2821,'Pierre Batcheff');
INSERT INTO acteur VALUES (2832,'Raymond Massey (I)');
INSERT INTO acteur VALUES (2834,'Shelley Winters');
INSERT INTO acteur VALUES (2872,'Walter Gotell');
INSERT INTO acteur VALUES (2881,'Kenny Baker (I)');
INSERT INTO acteur VALUES (2882,'Jason Flemyng');
INSERT INTO acteur VALUES (2883,'Ian Wolfe');
INSERT INTO acteur VALUES (2891,'Richard Bright');
INSERT INTO acteur VALUES (2894,'Scatman Crothers');
INSERT INTO acteur VALUES (2900,'Amy Wright');
INSERT INTO acteur VALUES (2905,'Brock Peters');
INSERT INTO acteur VALUES (2911,'Jay O. Sanders');
INSERT INTO acteur VALUES (2915,'Philip Stone (I)');
INSERT INTO acteur VALUES (2920,'Buck Henry');
INSERT INTO acteur VALUES (2935,'Ewen Bremner');
INSERT INTO acteur VALUES (2936,'Bo Hopkins');
INSERT INTO acteur VALUES (2937,'Alfred Molina');
INSERT INTO acteur VALUES (2939,'Leonard Rossiter');
INSERT INTO acteur VALUES (2941,'Catherine Keener');
INSERT INTO acteur VALUES (2942,'John Finn');
INSERT INTO acteur VALUES (2945,'Diane Ladd');
INSERT INTO acteur VALUES (2950,'Sheb Wooley');
INSERT INTO acteur VALUES (2953,'Mena Suvari');
INSERT INTO acteur VALUES (2957,'John Fiedler (I)');
INSERT INTO acteur VALUES (2973,'Leopoldo Trieste');
INSERT INTO acteur VALUES (2981,'David Andrews (I)');
INSERT INTO acteur VALUES (2986,'Clifton James');
INSERT INTO acteur VALUES (2991,'Siobhan Fallon');
INSERT INTO acteur VALUES (2998,'Philippe Morier-Genoud');
INSERT INTO acteur VALUES (2999,'Evelyn Keyes');
INSERT INTO acteur VALUES (3003,'Meat Loaf');
INSERT INTO acteur VALUES (3004,'Janet Margolin');
INSERT INTO acteur VALUES (3005,'Arthur O''Connell');
INSERT INTO acteur VALUES (3006,'John Ratzenberger');
INSERT INTO acteur VALUES (3017,'Harve Presnell');
INSERT INTO acteur VALUES (3018,'Peter Greene (I)');
INSERT INTO acteur VALUES (3020,'Harold Gould');
INSERT INTO acteur VALUES (3031,'L.Q. Jones');
INSERT INTO acteur VALUES (3039,'Henry Daniell');
INSERT INTO acteur VALUES (3046,'Gary Lewis (III)');
INSERT INTO acteur VALUES (3059,'Dylan Bruno');
INSERT INTO acteur VALUES (3065,'Alan North');
INSERT INTO acteur VALUES (3070,'Spencer Treat Clark');
INSERT INTO acteur VALUES (3074,'Lucas Black (II)');
INSERT INTO acteur VALUES (3101,'Patric Knowles');
INSERT INTO acteur VALUES (3107,'Hugh Marlowe');
INSERT INTO acteur VALUES (3110,'Hugh Griffith (I)');
INSERT INTO acteur VALUES (3111,'Paul Henreid');
INSERT INTO acteur VALUES (3119,'Jim Varney');
INSERT INTO acteur VALUES (3120,'Hoagy Carmichael');
INSERT INTO acteur VALUES (3123,'Ralph Carlsson');
INSERT INTO acteur VALUES (3124,'Charley Grapewin');
INSERT INTO acteur VALUES (3126,'Ralph Meeker');
INSERT INTO acteur VALUES (3127,'Howard St. John');
INSERT INTO acteur VALUES (3132,'Richard Basehart');
INSERT INTO acteur VALUES (3137,'Paulette Goddard');
INSERT INTO acteur VALUES (3138,'Stephen Young (I)');
INSERT INTO acteur VALUES (3141,'Sig Ruman');
INSERT INTO acteur VALUES (3149,'Scott Bakula');
INSERT INTO acteur VALUES (3153,'Fernando Fern�n G�mez');
INSERT INTO acteur VALUES (3157,'Stanislas Carr� de Malberg');
INSERT INTO acteur VALUES (3161,'James Gleason (I)');
INSERT INTO acteur VALUES (3165,'Theodore Bikel');
INSERT INTO acteur VALUES (3173,'Perry Lopez');
INSERT INTO acteur VALUES (3175,'Finlay Currie');
INSERT INTO acteur VALUES (3178,'Peter Mayhew (II)');
INSERT INTO acteur VALUES (3181,'Nigel Bruce');
INSERT INTO acteur VALUES (3190,'Raymond Burr');
INSERT INTO acteur VALUES (3198,'Srdjan Todorovic');
INSERT INTO acteur VALUES (3213,'Hattie McDaniel');
INSERT INTO acteur VALUES (3215,'Carol Cleveland');
INSERT INTO acteur VALUES (3228,'Jean Hagen');
INSERT INTO acteur VALUES (3233,'Moroni Olsen');
INSERT INTO acteur VALUES (3234,'Peter Cushing');
INSERT INTO acteur VALUES (3237,'Randy Brooks (I)');
INSERT INTO acteur VALUES (3243,'Dana Elcar');
INSERT INTO acteur VALUES (3244,'Peter Bull (I)');
INSERT INTO acteur VALUES (3247,'Marlene Dietrich');
INSERT INTO acteur VALUES (3253,'David Schofield');
INSERT INTO acteur VALUES (3260,'Josephine Hull');
INSERT INTO acteur VALUES (3261,'Anthony Higgins');
INSERT INTO acteur VALUES (3268,'Ruth White (II)');
INSERT INTO acteur VALUES (3273,'Sam Jaffe (I)');
INSERT INTO acteur VALUES (3280,'Andy Devine (I)');
INSERT INTO acteur VALUES (3298,'Arliss Howard');
INSERT INTO acteur VALUES (3301,'Barry Nelson (I)');
INSERT INTO acteur VALUES (3307,'Tracy Reed (I)');
INSERT INTO acteur VALUES (3312,'Michael Angarano');
INSERT INTO acteur VALUES (3326,'Donald O''Connor');
INSERT INTO acteur VALUES (3330,'Kate Hudson');
INSERT INTO acteur VALUES (3344,'Lee Strasberg');
INSERT INTO acteur VALUES (3345,'Louis Calhern');
INSERT INTO acteur VALUES (3347,'Rita Moreno');
INSERT INTO acteur VALUES (3362,'Maria de Medeiros');
INSERT INTO acteur VALUES (3366,'Margaret Dumont');
INSERT INTO acteur VALUES (3368,'Roscoe Karns');
INSERT INTO acteur VALUES (3370,'Dorothy Malone');
INSERT INTO acteur VALUES (3372,'Kirk Baltz');
INSERT INTO acteur VALUES (3377,'Dwight Yoakam');
INSERT INTO acteur VALUES (3379,'Joe Turkel');
INSERT INTO acteur VALUES (3390,'John Qualen');
INSERT INTO acteur VALUES (3397,'Rudy Bond');
INSERT INTO acteur VALUES (3403,'Lynne Thigpen');
INSERT INTO acteur VALUES (3413,'Michael Higgins (I)');
INSERT INTO acteur VALUES (3417,'Edie Adams');
INSERT INTO acteur VALUES (3419,'Peter Brocco');
INSERT INTO acteur VALUES (3422,'Reg E. Cathey');
INSERT INTO acteur VALUES (3425,'Sophie Marceau');
INSERT INTO acteur VALUES (3428,'Tommy Flanagan (I)');
INSERT INTO acteur VALUES (3434,'Eve Arden');
INSERT INTO acteur VALUES (3438,'Alida Valli');
INSERT INTO acteur VALUES (3449,'Paul Calderon');
INSERT INTO acteur VALUES (3481,'Dub Taylor');
INSERT INTO acteur VALUES (3498,'David Hemmings (I)');
INSERT INTO acteur VALUES (3500,'Robert Beatty (I)');
INSERT INTO acteur VALUES (3501,'Dimitra Arliss');
INSERT INTO acteur VALUES (3507,'Mandy Patinkin');
INSERT INTO acteur VALUES (3511,'Les Tremayne');
INSERT INTO acteur VALUES (3514,'Henry Victor');
INSERT INTO acteur VALUES (3523,'Jihmi Kennedy');
INSERT INTO acteur VALUES (3527,'Curt Bois');
INSERT INTO acteur VALUES (3530,'Estelle Harris');
INSERT INTO acteur VALUES (3533,'Horst Buchholz');
INSERT INTO acteur VALUES (3552,'George Raft');
INSERT INTO acteur VALUES (3561,'George Macready');
INSERT INTO acteur VALUES (3564,'Robert Ryan');
INSERT INTO acteur VALUES (3575,'Wilfrid Hyde-White');
INSERT INTO acteur VALUES (3586,'Lewis Martin (I)');
INSERT INTO acteur VALUES (3592,'Daisuke Kat� (I)');
INSERT INTO acteur VALUES (3619,'Ray Collins (I)');
INSERT INTO acteur VALUES (3637,'Larry Brandenburg');
INSERT INTO acteur VALUES (3646,'Leib Lensky');
INSERT INTO acteur VALUES (3655,'Ernest Thesiger');
INSERT INTO acteur VALUES (3664,'Chester Conklin');
INSERT INTO acteur VALUES (3677,'Don Keefer');
INSERT INTO acteur VALUES (3681,'Macdonald Carey');
INSERT INTO acteur VALUES (3697,'Sam Robards');
INSERT INTO acteur VALUES (3705,'Orson Bean');
INSERT INTO acteur VALUES (3707,'David Prowse');
INSERT INTO acteur VALUES (3729,'Cara Seymour');
INSERT INTO acteur VALUES (3733,'Sean Sullivan (I)');
INSERT INTO acteur VALUES (3737,'Norman Fell');
INSERT INTO acteur VALUES (3738,'Victor Jory (I)');
INSERT INTO acteur VALUES (3739,'John Shrapnel');
INSERT INTO acteur VALUES (3740,'Elisha Cook Jr.');
INSERT INTO acteur VALUES (3750,'Mischa Barton');
INSERT INTO acteur VALUES (3756,'Jens Albinus');
INSERT INTO acteur VALUES (3761,'Thelma Ritter');
INSERT INTO acteur VALUES (3767,'John Ridgely');
INSERT INTO acteur VALUES (3774,'Minna Gombell');
INSERT INTO acteur VALUES (3792,'Edward Brophy');
INSERT INTO acteur VALUES (3794,'James Sloyan');
INSERT INTO acteur VALUES (3796,'Michael Berryman');
INSERT INTO acteur VALUES (3797,'Marisa Paredes');
INSERT INTO acteur VALUES (3809,'Fortunio Bonanova');
INSERT INTO acteur VALUES (3821,'Richard Davalos');
INSERT INTO acteur VALUES (3827,'John Clive');
INSERT INTO acteur VALUES (3838,'Brent Briscoe');
INSERT INTO acteur VALUES (3844,'Tim Holt');
INSERT INTO acteur VALUES (3846,'Vinnie Jones');
INSERT INTO acteur VALUES (3857,'Conrad Veidt');
INSERT INTO acteur VALUES (3858,'Scott Schwartz');
INSERT INTO acteur VALUES (3861,'Daniel Zacapa');
INSERT INTO acteur VALUES (3865,'Connie Booth');
INSERT INTO acteur VALUES (3871,'Coleen Gray');
INSERT INTO acteur VALUES (3883,'Sandy Dennis');
INSERT INTO acteur VALUES (3898,'Samuel Le Bihan');
INSERT INTO acteur VALUES (3902,'Collin Wilcox Paxton');
INSERT INTO acteur VALUES (3907,'Colleen Dewhurst');
INSERT INTO acteur VALUES (3910,'Danny Lloyd');
INSERT INTO acteur VALUES (3914,'Colin Clive');
INSERT INTO acteur VALUES (3916,'Sandy Nelson (II)');
INSERT INTO acteur VALUES (3921,'Danny Lee (I)');
INSERT INTO acteur VALUES (3952,'Dana Andrews');
INSERT INTO acteur VALUES (3956,'Seiji Miyaguchi');
INSERT INTO acteur VALUES (3966,'Ruth Hussey');
INSERT INTO acteur VALUES (3970,'Ruth Roman');
INSERT INTO acteur VALUES (3971,'Sergio Bini Bustric');
INSERT INTO acteur VALUES (3985,'Sessue Hayakawa');
INSERT INTO acteur VALUES (3987,'Daisuke Ryu');
INSERT INTO acteur VALUES (3988,'Rosemary Murphy');
INSERT INTO acteur VALUES (3991,'Sean Lawlor');
INSERT INTO acteur VALUES (4000,'Seizabur� Kawazu');
INSERT INTO acteur VALUES (4004,'Daniel Richter (I)');
INSERT INTO acteur VALUES (4022,'Salvador Dal�');
INSERT INTO acteur VALUES (4023,'Sally Yeh (I)');
INSERT INTO acteur VALUES (4052,'Vin�cius de Oliveira');
INSERT INTO acteur VALUES (4060,'Anne Reid');
INSERT INTO acteur VALUES (4073,'Antonia San Juan');
INSERT INTO acteur VALUES (4082,'Victor McLaglen');
INSERT INTO acteur VALUES (4093,'Virginia Mayo');
INSERT INTO acteur VALUES (4124,'Barton MacLane');
INSERT INTO acteur VALUES (4133,'Barbara Stanwyck');
INSERT INTO acteur VALUES (4141,'Bengt Ekerot');
INSERT INTO acteur VALUES (4154,'Armando Brancia');
INSERT INTO acteur VALUES (4159,'Arnold Lucy');
INSERT INTO acteur VALUES (4169,'Andrew Kevin Walker');
INSERT INTO acteur VALUES (4171,'Ayano Shiraishi');
INSERT INTO acteur VALUES (4174,'Barbara Bel Geddes');
INSERT INTO acteur VALUES (4178,'Valerie Hobson');
INSERT INTO acteur VALUES (4182,'Avery Brooks');
INSERT INTO acteur VALUES (4188,'B�rje Ahlstedt');
INSERT INTO acteur VALUES (4190,'Yoshiko Shinohara');
INSERT INTO acteur VALUES (4195,'Y�ko Tanaka');
INSERT INTO acteur VALUES (4196,'Alan Hale');
INSERT INTO acteur VALUES (4199,'Akim Tamiroff');
INSERT INTO acteur VALUES (4201,'Akihiro Miwa');
INSERT INTO acteur VALUES (4202,'Akemi Yamaguchi');
INSERT INTO acteur VALUES (4207,'Albert R�my');
INSERT INTO acteur VALUES (4209,'William Sylvester');
INSERT INTO acteur VALUES (4218,'Wolfgang Heinz');
INSERT INTO acteur VALUES (4233,'Zeppo Marx');
INSERT INTO acteur VALUES (4236,'Zhang Ziyi');
INSERT INTO acteur VALUES (4241,'Yoshio Inaba');
INSERT INTO acteur VALUES (4242,'Agnes Moorehead');
INSERT INTO acteur VALUES (4248,'Yuriko Ishida');
INSERT INTO acteur VALUES (4253,'Adolphe Menjou');
INSERT INTO acteur VALUES (4258,'Aldo Giuffr�');
INSERT INTO acteur VALUES (4259,'Wayne Morris (I)');
INSERT INTO acteur VALUES (4260,'Wendell Corey');
INSERT INTO acteur VALUES (4274,'Walter Huston');
INSERT INTO acteur VALUES (4278,'Walter Catlett');
INSERT INTO acteur VALUES (4283,'Allan Jones');
INSERT INTO acteur VALUES (4293,'William Hope');
INSERT INTO acteur VALUES (4304,'William Redfield');
INSERT INTO acteur VALUES (4309,'Aldo Silvani (I)');
INSERT INTO acteur VALUES (4323,'Alexander Granach');
INSERT INTO acteur VALUES (4324,'Wes Bentley');
INSERT INTO acteur VALUES (4335,'Chen Chang');
INSERT INTO acteur VALUES (4339,'Charles Smith (V)');
INSERT INTO acteur VALUES (4340,'Charles Ruggles');
INSERT INTO acteur VALUES (4344,'Stephen Boyd');
INSERT INTO acteur VALUES (4352,'Charles Kay');
INSERT INTO acteur VALUES (4362,'Cathy O''Donnell (I)');
INSERT INTO acteur VALUES (4389,'Celeste Holm');
INSERT INTO acteur VALUES (4392,'Cecil Parker (I)');
INSERT INTO acteur VALUES (4396,'Soia Lira');
INSERT INTO acteur VALUES (4399,'Claire Maurier');
INSERT INTO acteur VALUES (4401,'Clarence Kolb');
INSERT INTO acteur VALUES (4403,'Slim Summerville');
INSERT INTO acteur VALUES (4408,'Ciccio Ingrassia');
INSERT INTO acteur VALUES (4415,'Cliff Edwards');
INSERT INTO acteur VALUES (4417,'Simone Mareuil');
INSERT INTO acteur VALUES (4428,'Stefan H�rberg');
INSERT INTO acteur VALUES (4450,'Chu Kong');
INSERT INTO acteur VALUES (4492,'Branka Katic');
INSERT INTO acteur VALUES (4503,'Beulah Bondi');
INSERT INTO acteur VALUES (4504,'Tiny Sandford');
INSERT INTO acteur VALUES (4510,'Bert Lahr');
INSERT INTO acteur VALUES (4526,'Tom Murray (I)');
INSERT INTO acteur VALUES (4535,'Candela Pe�a');
INSERT INTO acteur VALUES (4552,'Carrie Henn');
INSERT INTO acteur VALUES (4594,'Bruce Bennett');
INSERT INTO acteur VALUES (4601,'Jinpachi Nezu');
INSERT INTO acteur VALUES (4608,'Jo Van Fleet');
INSERT INTO acteur VALUES (4619,'Jo Prestia');
INSERT INTO acteur VALUES (4628,'Joan Shawlee');
INSERT INTO acteur VALUES (4636,'Joanne Dru');
INSERT INTO acteur VALUES (4657,'Mathias Rust (I)');
INSERT INTO acteur VALUES (4662,'Jim Farley (I)');
INSERT INTO acteur VALUES (4684,'John Megna');
INSERT INTO acteur VALUES (4705,'John Terry (I)');
INSERT INTO acteur VALUES (4716,'John Ireland');
INSERT INTO acteur VALUES (4736,'Millard Mitchell');
INSERT INTO acteur VALUES (4738,'Mervyn Johns');
INSERT INTO acteur VALUES (4741,'Melville Cooper');
INSERT INTO acteur VALUES (4743,'John Howard (I)');
INSERT INTO acteur VALUES (4749,'John Gottowt');
INSERT INTO acteur VALUES (4755,'John Farley');
INSERT INTO acteur VALUES (4761,'Jamie Draven');
INSERT INTO acteur VALUES (4762,'Jamie Bell');
INSERT INTO acteur VALUES (4788,'Jane Darwell');
INSERT INTO acteur VALUES (4790,'Nicholas Colasanto (I)');
INSERT INTO acteur VALUES (4805,'Nikolai Sergeyev');
INSERT INTO acteur VALUES (4815,'Othon Bastos');
INSERT INTO acteur VALUES (4817,'Nils Poppe');
INSERT INTO acteur VALUES (4822,'Nobuo Kaneko');
INSERT INTO acteur VALUES (4836,'Myron McCormick');
INSERT INTO acteur VALUES (4851,'Jean-Pierre Lorit');
INSERT INTO acteur VALUES (4865,'Jeffrey Hunter');
INSERT INTO acteur VALUES (4883,'Natalie Canerday');
INSERT INTO acteur VALUES (4884,'Ned Bellamy');
INSERT INTO acteur VALUES (4895,'Nat Pendleton');
INSERT INTO acteur VALUES (4898,'Jean-Louis Trintignant');
INSERT INTO acteur VALUES (4899,'Jean-Louis Barrault');
INSERT INTO acteur VALUES (4900,'Nancy Olson');
INSERT INTO acteur VALUES (4901,'Nando Orfei');
INSERT INTO acteur VALUES (4908,'Natacha R�gnier');
INSERT INTO acteur VALUES (4909,'Jean Heywood');
INSERT INTO acteur VALUES (4910,'Jean Heather');
INSERT INTO acteur VALUES (4918,'Kristin Rudr�d');
INSERT INTO acteur VALUES (4919,'Kristian Almgren');
INSERT INTO acteur VALUES (4923,'Machiko Ky�');
INSERT INTO acteur VALUES (4924,'Klaus Wennemann');
INSERT INTO acteur VALUES (4927,'Kitty Carlisle');
INSERT INTO acteur VALUES (4946,'Ky�ko Seki');
INSERT INTO acteur VALUES (4949,'Kumeko Urabe');
INSERT INTO acteur VALUES (4952,'Mack Swain');
INSERT INTO acteur VALUES (4957,'Kevin P. Farley');
INSERT INTO acteur VALUES (4966,'Mar�lia P�ra');
INSERT INTO acteur VALUES (4971,'John Wray (I)');
INSERT INTO acteur VALUES (4977,'Madeleine LeBeau');
INSERT INTO acteur VALUES (4981,'Makoto Kobori');
INSERT INTO acteur VALUES (4985,'Madison Lanc');
INSERT INTO acteur VALUES (4992,'Kim Novak');
INSERT INTO acteur VALUES (5002,'Leopoldine Konstantin');
INSERT INTO acteur VALUES (5003,'Leslie Howard');
INSERT INTO acteur VALUES (5006,'Leonard Harris (II)');
INSERT INTO acteur VALUES (5010,'Leo Gullotta');
INSERT INTO acteur VALUES (5011,'Ljubica Adzovic');
INSERT INTO acteur VALUES (5017,'Lionel Atwill');
INSERT INTO acteur VALUES (5019,'Lillian Gish');
INSERT INTO acteur VALUES (5034,'Louis Wolheim');
INSERT INTO acteur VALUES (5064,'Lou Antonio');
INSERT INTO acteur VALUES (5068,'Lawrence T. Wrentz');
INSERT INTO acteur VALUES (5070,'Lawrence A. Bonney');
INSERT INTO acteur VALUES (5085,'Martha Vickers');
INSERT INTO acteur VALUES (5126,'Masayuki Mori (I)');
INSERT INTO acteur VALUES (5132,'Martin Semmelrogge');
INSERT INTO acteur VALUES (5136,'Joseph Calleia');
INSERT INTO acteur VALUES (5138,'Jonathan Sagall');
INSERT INTO acteur VALUES (5139,'Zooey Deschanel');
INSERT INTO acteur VALUES (5160,'Maria Casar�s');
INSERT INTO acteur VALUES (5163,'Kathleen Harrison');
INSERT INTO acteur VALUES (5173,'Marcella Rovere');
INSERT INTO acteur VALUES (5177,'Katy Jurado');
INSERT INTO acteur VALUES (5195,'Jullan Kindahl');
INSERT INTO acteur VALUES (5201,'Julien Carette');
INSERT INTO acteur VALUES (5214,'Karl Etlinger');
INSERT INTO acteur VALUES (5223,'Kaoru Kobayashi');
INSERT INTO acteur VALUES (5239,'Francine Racette');
INSERT INTO acteur VALUES (5242,'Fr�d�rique Feder');
INSERT INTO acteur VALUES (5254,'Frank Morgan (I)');
INSERT INTO acteur VALUES (5258,'Florijan Ajdini');
INSERT INTO acteur VALUES (5264,'Francis De Wolff');
INSERT INTO acteur VALUES (5272,'Richmond Arquette');
INSERT INTO acteur VALUES (5273,'Evelyn Varden');
INSERT INTO acteur VALUES (5279,'Eva Marie Saint');
INSERT INTO acteur VALUES (5281,'Eugene Pallette');
INSERT INTO acteur VALUES (5297,'Felix Bressart');
INSERT INTO acteur VALUES (5300,'Richard S. Castellano');
INSERT INTO acteur VALUES (5312,'Raphael Fejt�');
INSERT INTO acteur VALUES (5318,'Ray Bolger');
INSERT INTO acteur VALUES (5330,'Georgia Hale');
INSERT INTO acteur VALUES (5342,'Georges Flamant');
INSERT INTO acteur VALUES (5358,'Richard Allen (I)');
INSERT INTO acteur VALUES (5359,'Richard Anderson (I)');
INSERT INTO acteur VALUES (5364,'Gary Merrill');
INSERT INTO acteur VALUES (5365,'Gary Lockwood');
INSERT INTO acteur VALUES (5378,'Reginald Gardiner');
INSERT INTO acteur VALUES (5382,'Dorris Bowdon');
INSERT INTO acteur VALUES (5392,'Douglas Rain');
INSERT INTO acteur VALUES (5403,'Edmond O''Brien');
INSERT INTO acteur VALUES (5410,'Dorothy Comingore');
INSERT INTO acteur VALUES (5413,'Ed Begley');
INSERT INTO acteur VALUES (5416,'Robert Walker (I)');
INSERT INTO acteur VALUES (5435,'Dita Parlo');
INSERT INTO acteur VALUES (5441,'Donnie Wahlberg');
INSERT INTO acteur VALUES (5448,'Edward Arnold');
INSERT INTO acteur VALUES (5462,'Enzo Cannavale');
INSERT INTO acteur VALUES (5489,'Erica Carlson (II)');
INSERT INTO acteur VALUES (5490,'Eric Weinstein');
INSERT INTO acteur VALUES (5501,'Eleanor Coppola');
INSERT INTO acteur VALUES (5507,'Eijir� Tono');
INSERT INTO acteur VALUES (5511,'Edward Everett Horton');
INSERT INTO acteur VALUES (5527,'Robert Drivas');
INSERT INTO acteur VALUES (5529,'Elizabeth Berridge');
INSERT INTO acteur VALUES (5540,'Harriet Andersson');
INSERT INTO acteur VALUES (5545,'Paul Simon (I)');
INSERT INTO acteur VALUES (5546,'Herbert Gr�nemeyer');
INSERT INTO acteur VALUES (5554,'Hubertus Bengsch');
INSERT INTO acteur VALUES (5556,'Paul H�rbiger');
INSERT INTO acteur VALUES (5570,'Peter Billingsley');
INSERT INTO acteur VALUES (5572,'Pernilla Allwin');
INSERT INTO acteur VALUES (5573,'Pernilla August');
INSERT INTO acteur VALUES (5574,'Haya Harareet');
INSERT INTO acteur VALUES (5577,'Harvey Lembeck');
INSERT INTO acteur VALUES (5586,'Harry Carey Jr.');
INSERT INTO acteur VALUES (5592,'Rebecka Liljeberg');
INSERT INTO acteur VALUES (5608,'Patricia Hitchcock');
INSERT INTO acteur VALUES (5610,'Jack Elam');
INSERT INTO acteur VALUES (5611,'Jack Creley');
INSERT INTO acteur VALUES (5614,'Jack Benny');
INSERT INTO acteur VALUES (5615,'J.D. Cannon');
INSERT INTO acteur VALUES (5618,'Jack Haley (I)');
INSERT INTO acteur VALUES (5623,'Ivan Lapikov');
INSERT INTO acteur VALUES (5626,'Patricia Collinge');
INSERT INTO acteur VALUES (5632,'Jackie Gleason');
INSERT INTO acteur VALUES (5638,'Jack Oakie');
INSERT INTO acteur VALUES (5641,'Pat Henning');
INSERT INTO acteur VALUES (5643,'Pat O''Brien');
INSERT INTO acteur VALUES (5651,'Ian Petrella');
INSERT INTO acteur VALUES (5665,'Ingrid Thulin');
INSERT INTO acteur VALUES (5668,'Patrick Fugit');
INSERT INTO acteur VALUES (5669,'Isa Danieli');
INSERT INTO acteur VALUES (5670,'Irma Raush');
INSERT INTO acteur VALUES (5683,'Patrick Mercado');
INSERT INTO acteur VALUES (5684,'Giulietta Masina');
INSERT INTO acteur VALUES (5685,'Giuliana Lojodice');
INSERT INTO acteur VALUES (5692,'Giustino Durano');
INSERT INTO acteur VALUES (5700,'Pierre Brasseur');
INSERT INTO acteur VALUES (5705,'Philip Ober');
INSERT INTO acteur VALUES (5709,'Guy Decomble');
INSERT INTO acteur VALUES (5710,'Pierre Renoir');
INSERT INTO acteur VALUES (5714,'Gloria Swanson');
INSERT INTO acteur VALUES (5715,'Glen Cavender');
INSERT INTO acteur VALUES (5717,'Guy Kibbee');
INSERT INTO acteur VALUES (5718,'Pierre Fresnay');
INSERT INTO acteur VALUES (5727,'Priscilla Lane');
INSERT INTO acteur VALUES (5759,'William Hootkins');
INSERT INTO acteur VALUES (5770,'Frank Adonis');
INSERT INTO acteur VALUES (5776,'Jack Walsh (I)');
INSERT INTO acteur VALUES (5777,'Jude Ciccolella');
INSERT INTO acteur VALUES (5778,'Shane Rimmer');
INSERT INTO acteur VALUES (5779,'Norbert Weisser');
INSERT INTO acteur VALUES (5788,'Jack Purvis');
INSERT INTO acteur VALUES (5791,'James Keane (I)');
INSERT INTO acteur VALUES (5799,'George Furth');
INSERT INTO acteur VALUES (5800,'Edward Bunker');
INSERT INTO acteur VALUES (5811,'Benito Stefanelli');
INSERT INTO acteur VALUES (5813,'Eddra Gale');
INSERT INTO acteur VALUES (5829,'Octavia Spencer');
INSERT INTO acteur VALUES (5840,'Una O''Connor');
INSERT INTO acteur VALUES (5842,'Godfrey Quigley');
INSERT INTO acteur VALUES (5861,'Darrell Zwerling');
INSERT INTO acteur VALUES (5862,'Henry Brandon');
INSERT INTO acteur VALUES (5863,'Andr� Morell');
INSERT INTO acteur VALUES (5866,'Frank Sivero');
INSERT INTO acteur VALUES (5883,'Joyce Jameson');
INSERT INTO acteur VALUES (5904,'Paul Fix');
INSERT INTO acteur VALUES (5924,'H.B. Warner');
INSERT INTO acteur VALUES (5934,'Regis Toomey');
INSERT INTO acteur VALUES (5936,'Manning Redwood');
INSERT INTO acteur VALUES (5944,'Ken Curtis (I)');